"""Starting and stopping the app, and knowing whether it is up.

The launcher is a generated POSIX shell script rather than a call into this process,
for the same reason it is in the research app: choosing a free port and holding it
exclusively has to survive this process exiting, or two commands asked to start the app
at the same moment both decide the same port is free.

The state lives beside the account's global memory rather than inside a project,
because there is one app for the account and not one per project. A project's own
repository holds its local memory and nothing of the app's, which is what lets a
project be moved, copied, or shared without carrying a port number with it.
"""

from __future__ import annotations

import os
import signal
import subprocess
import sys
import time
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .app import PID_FILE, PORT_FILE, UI_HOST

#: The directory under the storage root that holds the app's machine-local state.
STATE_DIRNAME = "app"
LAUNCHER_DIRECTORY = "bin"
LAUNCHER_NAME = "memory-rag-app.sh"
LOG_NAME = "memory-rag.log"
#: The port the app asks for first. A command that needs a fixed port says so, and the
#: script walks forward from here when this one is taken.
DEFAULT_UI_PORT = 5051
#: The project-root name a person double-clicks. It is a symlink, so it is a fact of
#: this machine rather than something a project carries between them.
LINK_NAME = "open-memory-rag-ui.sh"
#: The marker that says which build wrote the script. The version is part of it
#: because a template change within one product is exactly the case a bare product
#: name misses: the file would pass the check and run a command this build no longer
#: accepts, and the failure would appear only in a log nobody opens.
LAUNCHER_MARKER = "memory-rag-app"
#: How long `stop` waits after SIGTERM before it escalates.
STOP_TIMEOUT_SECONDS = 5.0


def state_root(storage_root: Path) -> Path:
    """Return the machine-local state directory for this account's app."""

    return storage_root / STATE_DIRNAME


def launcher_path(storage_root: Path) -> Path:
    """Return where the generated launcher lives."""

    return state_root(storage_root) / LAUNCHER_DIRECTORY / LAUNCHER_NAME


def log_path(storage_root: Path) -> Path:
    return state_root(storage_root) / LOG_NAME


def port_file(storage_root: Path) -> Path:
    return state_root(storage_root) / PORT_FILE


def pid_file(storage_root: Path) -> Path:
    return state_root(storage_root) / PID_FILE


_TEMPLATE = """#!/bin/sh
# {marker} {version}: generated by memory-rag. Machine-local, holds nothing of yours,
# safe to delete: the next `memory-rag start` writes a new one.
set -u

STATE="{state}"
# The storage root this launcher's own state lives under. It is handed to the app it
# starts, because a launcher that chose a port and wrote a pid file for one account
# while starting an app configured for another is two installations that agree about
# nothing, and the one that answers is whichever the environment happened to select.
STORAGE="{storage}"
PORT_FILE="$STATE/{port_file}"
PID_FILE="$STATE/{pid_file}"
LOG="$STATE/{log}"
LOCK="$STATE/start.lock"
DEFAULT_PORT={default_port}

mkdir -p "$STATE/logs" 2>/dev/null || true

free_port() {{
  # The first port at or above $1 with nothing listening on it, tried 200 times. A
  # port in TIME_WAIT after a stop is reusable, so this is a bind test rather than a
  # check of a file.
  candidate=$1
  tries=0
  while [ "$tries" -lt 200 ]; do
    if command -v python3 >/dev/null 2>&1; then
      if python3 -c "import socket,sys
s=socket.socket()
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
try:
    s.bind(('{host}', int(sys.argv[1])))
except OSError:
    sys.exit(1)
finally:
    s.close()" "$candidate" 2>/dev/null; then
        printf '%s' "$candidate"
        return 0
      fi
    fi
    candidate=$((candidate + 1))
    tries=$((tries + 1))
  done
  return 1
}}

stop_app() {{
  if [ ! -f "$PID_FILE" ]; then
    echo "memory-rag: no app is recorded as running."
    exit 0
  fi
  pid=$(cat "$PID_FILE" 2>/dev/null || true)
  case "$pid" in
    ''|*[!0-9]*)
      echo "memory-rag: the pid file does not hold a number; removing it."
      rm -f "$PID_FILE" "$PORT_FILE"
      exit 0
      ;;
  esac
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "memory-rag: no process is running with pid $pid; removing its record."
    rm -f "$PID_FILE" "$PORT_FILE"
    exit 0
  fi
  # The recorded pid has to still be this app's own process, for this account. A pid
  # file outlives its process and the number gets reused, so a stop that trusted the
  # number alone would signal whatever the machine happened to run next. Two things are
  # checked rather than one: the program the command line actually runs, read from its
  # first argument or from the module an interpreter was given, and the account it was
  # told to serve, read from the `--storage-root` this launcher starts the app with.
  ours=no
  program=
  root=
  previous=
  while IFS= read -r argument; do
    if [ -z "$program" ]; then program=$argument; fi
    if [ "$previous" = "--storage-root" ]; then root=$argument; fi
    previous=$argument
  done <<EOF
$(tr '\\0' '\\n' < "/proc/$pid/cmdline" 2>/dev/null)
EOF
  case "${{program##*/}}" in
    memory-rag|memory-rag.py|memory_rag|memory_rag.py)
      ours=yes
      ;;
    python|python3|python3.*|pypy|pypy3)
      if tr '\\0' '\\n' < "/proc/$pid/cmdline" 2>/dev/null \\
        | grep -qx -e memory_rag -e memory-rag; then
        ours=yes
      fi
      ;;
  esac
  if [ "$ours" = no ] || [ "$root" != "$STORAGE" ]; then
    echo "memory-rag: pid $pid is not this account's app, so it was left alone;" \\
      "removing the record instead." >&2
    rm -f "$PID_FILE" "$PORT_FILE"
    exit 0
  fi
  kill -TERM "$pid" 2>/dev/null || true
  waited=0
  limit={stop_timeout}
  while [ "$waited" -lt "$limit" ]; do
    if ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$PID_FILE" "$PORT_FILE"
      echo "memory-rag: stopped the app with pid $pid."
      exit 0
    fi
    sleep 1
    waited=$((waited + 1))
  done
  kill -KILL "$pid" 2>/dev/null || true
  sleep 1
  if kill -0 "$pid" 2>/dev/null; then
    echo "memory-rag: pid $pid ignored SIGTERM and SIGKILL; remove it by hand." >&2
    exit 1
  fi
  rm -f "$PID_FILE" "$PORT_FILE"
  echo "memory-rag: stopped the app with pid $pid."
}}

case "${{1:-}}" in
  --stop)
    stop_app
    ;;
  --help|-h)
    echo "Generated by memory-rag. Takes --port N, --open, or --stop."
    ;;
esac

# One start at a time, or two commands pick the same port and one of them loses the
# claim after it has already written its pid file.
if ! mkdir "$LOCK" 2>/dev/null; then
  stale=$(cat "$LOCK/pid" 2>/dev/null || true)
  if [ -n "$stale" ] && ! kill -0 "$stale" 2>/dev/null; then
    rm -rf "$LOCK"
    mkdir "$LOCK" 2>/dev/null || exit 1
  else    echo "memory-rag: another start is already choosing a port; wait for it." >&2
    exit 1
  fi
fi
echo $$ > "$LOCK/pid"
trap 'rm -rf "$LOCK"' EXIT INT TERM

# The command to run is this script's arguments, so the options this script reads are
# taken off the front of them and the rest is left in place for the app. A loop that
# shifted every argument would consume the command too and run nothing at all.
requested=$DEFAULT_PORT
open_browser=no
command=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --port)
      shift
      requested=${{1:-$DEFAULT_PORT}}
      shift
      ;;
    --port=*)
      requested=${{1#--port=}}
      shift
      ;;
    --open|-o)
      open_browser=yes
      shift
      ;;
    --)
      shift
      command="$*"
      break
      ;;
    -*)
      echo "memory-rag: $1 is not an option this launcher takes." >&2
      exit 1
      ;;
    *)
      # The first argument that is not an option starts the command, and everything
      # from there on belongs to it.
      command="$*"
      break
      ;;
  esac
done

if [ -z "$command" ]; then
  echo "memory-rag: this launcher needs a command to run, e.g. the serve subcommand." >&2
  exit 1
fi

PORT=$(free_port "$requested")
if [ -z "$PORT" ]; then
  echo "memory-rag: no free port from $requested upward; pass --port to choose one." >&2
  exit 1
fi

# The command's own global option comes before the subcommand and the subcommand's own
# option after it, because that is the only order the parser accepts: a global option
# placed after `serve` is rejected outright, and an option the app owns placed before it
# is never read. Getting this order wrong fails into the log above and nowhere else, so
# the integration test runs this script as written rather than trusting it.
printf '%s' "$PORT" > "$PORT_FILE"

# The app is put in its own session when the system can do it, so that the shell that
# started it going away does not take it with it. A terminal that is closed, or a
# parent process group that is reaped, would otherwise end an app that was supposed to
# outlive the command. Without setsid the app still starts; it just lives as long as
# whatever started it, which is not what `memory-rag start` promises.
if command -v setsid >/dev/null 2>&1; then
  # shellcheck disable=SC2086
  setsid $command --storage-root "$STORAGE" serve --port "$PORT" >>"$LOG" 2>&1 &
else
  # shellcheck disable=SC2086
  $command --storage-root "$STORAGE" serve --port "$PORT" >>"$LOG" 2>&1 &
fi
app_pid=$!
printf '%s' "$app_pid" > "$PID_FILE"

# Wait for the port to answer rather than for the process to exist, because a process
# that has started and is still loading a model is not yet serving.
waited=0
served=no
while [ "$waited" -lt 120 ]; do
  if command -v python3 >/dev/null 2>&1; then
    if python3 -c "import socket,sys
s=socket.socket()
s.settimeout(1)
try:
    s.connect(('{host}', int(sys.argv[1])))
except OSError:
    sys.exit(1)
finally:
    s.close()" "$PORT" 2>/dev/null; then
      served=yes
      break
    fi
  fi
  if ! kill -0 "$app_pid" 2>/dev/null; then
    echo "memory-rag: the app exited before it served. Read $LOG" >&2
    rm -f "$PID_FILE" "$PORT_FILE"
    exit 1
  fi
  sleep 1
  waited=$((waited + 1))
done

# An app that is still loading its models after two minutes is a start that has not
# worked, and printing an address for it is the one answer a reader cannot act on: the
# connection is refused by a port nothing is listening on. The record is kept, because
# the process is alive and `memory-rag stop` has to be able to find it.
if [ "$served" != yes ]; then
  echo "memory-rag: the app did not answer on port $PORT within 120 seconds. Read $LOG" >&2
  exit 1
fi

case "$open_browser" in
  yes)
    command -v xdg-open >/dev/null 2>&1 && xdg-open "http://{host}:$PORT" >/dev/null 2>&1
    command -v open >/dev/null 2>&1 && open "http://{host}:$PORT" >/dev/null 2>&1
    ;;
esac

echo "memory-rag: the app is at http://{host}:$PORT"
echo "memory-rag: its log is $LOG"
exit 0
"""


def launcher_script(storage_root: Path) -> str:
    """Return the launcher this build would write."""

    from . import __version__

    return _TEMPLATE.format(
        marker=LAUNCHER_MARKER,
        version=__version__,
        state=state_root(storage_root),
        storage=storage_root,
        port_file=PORT_FILE,
        pid_file=PID_FILE,
        log=LOG_NAME,
        default_port=DEFAULT_UI_PORT,
        stop_timeout=int(STOP_TIMEOUT_SECONDS),
        host=UI_HOST,
    )


def ensure_launcher(storage_root: Path) -> Path:
    """Write the launcher if it is missing or was written by another build.

    The file is machine-local and holds nothing of the user's, so replacing it is safe.
    A file this build did not write may run a command this one no longer accepts, and
    running it would fail in a log nobody opens.
    """

    target = launcher_path(storage_root)
    if target.is_file() and launcher_is_current(target):
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(launcher_script(storage_root), encoding="utf-8")
    target.chmod(0o755)
    return target


def launcher_is_current(script: Path) -> bool:
    """Whether a launcher was written by this version of this build.

    The marker is a whole line rather than a substring, because a path or an argument
    may contain the same words and a substring match would read a stale file as
    current. The version is compared as well, so a template change rewrites the file
    rather than leaving an older command in place.
    """

    from . import __version__

    wanted = f"# {LAUNCHER_MARKER} {__version__}:"
    try:
        for line in script.read_text(encoding="utf-8").splitlines():
            if line.startswith(wanted):
                return True
    except OSError:
        return False
    return False


def link_path(project_root: Path) -> Path:
    """Return the double-clickable name inside a project."""

    return project_root / LINK_NAME


def ensure_link(project_root: Path, storage_root: Path) -> str:
    """Point a project's double-clickable name at the account's launcher.

    The link is machine-local and is never overwritten if it points somewhere else, so
    a project keeps whatever the user put there.
    """

    target = launcher_path(storage_root)
    link = link_path(project_root)
    if link.is_symlink():
        if os.readlink(link) == str(target):
            return "current"
        link.unlink()
    elif link.exists():
        return "left alone: a file of that name is already there"
    link.symlink_to(target)
    return "written"


def recorded_port(storage_root: Path) -> int | None:
    """The port the launcher recorded, or None when it recorded none."""

    try:
        return int(port_file(storage_root).read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None


#: The names this app's own process is started under: the console script and the module
#: `python -m` runs. These are whole names rather than substrings, because a substring
#: match reads any process that merely mentions this product as this one — and the
#: repository directory itself is called `memory-rag`.
PROCESS_MARKERS = ("memory_rag", "memory-rag")

#: Interpreter program names, so `-m` is only read after one of them. A path to an
#: interpreter is judged on its own name, which is what a distribution calls it.
_INTERPRETER_NAMES = frozenset(
    {"python", "python3", "python3.11", "python3.12", "python3.13", "pypy", "pypy3"}
)

#: Interpreter flags that take no value, so the next argument after one of them is still
#: the interpreter's own.
_INTERPRETER_FLAGS_WITHOUT_VALUE = frozenset(
    {"-B", "-b", "-E", "-h", "-I", "-i", "-O", "-q", "-s", "-S", "-u", "-v", "-V", "-x"}
)

#: Interpreter flags whose value is the next argument, so that argument is the flag's and
#: names no program.
_INTERPRETER_FLAGS_WITH_VALUE = frozenset({"-c", "-W", "-X"})


def _program_of(arguments: Sequence[str]) -> str | None:
    """Return the program a command line actually runs, or None when it cannot tell.

    The program is the first argument, or the module named by an interpreter's `-m`.
    Code handed to the interpreter as a string — `-c`, or `-` — names no program this
    product owns, and neither does a flag whose value happens to be the product's name.
    Looking further along the line is how an editor with a path open or a test runner on
    a path under this repository is read as this app.
    """

    if not arguments:
        return None
    first = arguments[0]
    if _is_entry_point(first):
        return first
    if Path(first).stem.lower() not in _INTERPRETER_NAMES:
        return None
    index = 1
    while index < len(arguments):
        argument = arguments[index]
        if argument == "--":
            return None
        if argument == "-m":
            following = arguments[index + 1] if index + 1 < len(arguments) else ""
            return following if _is_entry_point(following) else None
        if argument in _INTERPRETER_FLAGS_WITH_VALUE:
            return None
        if argument not in _INTERPRETER_FLAGS_WITHOUT_VALUE:
            return None
        index += 1
    return None


def process_arguments(pid: int) -> list[str] | None:
    """Return a live process's arguments, or None when they cannot be read."""

    try:
        raw = Path(f"/proc/{pid}/cmdline").read_bytes().decode("utf-8", "replace")
    except OSError:
        # A process that ended between the check above and this read is not ours to
        # signal, and there is no portable way to ask on every system.
        return None
    return [part for part in raw.split("\0") if part]


def process_storage_root(arguments: Sequence[str], environ: str) -> Path | None:
    """Return the account a running process was told to serve, or None when unreadable.

    This is the rule the app itself applies to its own inputs — the option first, then
    the two environment names, then the default — read off the process rather than off
    this one, so two accounts on one machine cannot be told apart by a pid file alone.
    """

    from .config import (
        STORAGE_ENV_VAR,
        ULTRARAG_STORAGE_ENV_VAR,
        default_storage_root,
    )

    named = _named_value(arguments, "--storage-root")
    if named is not None:
        return Path(named).expanduser().resolve()
    environment = dict(
        pair.split("=", 1) for pair in environ.split("\0") if "=" in pair
    )
    for name in (STORAGE_ENV_VAR, ULTRARAG_STORAGE_ENV_VAR):
        value = environment.get(name, "").strip()
        if value:
            return Path(value).expanduser().resolve()
    return default_storage_root().expanduser().resolve()


def _named_value(arguments: Sequence[str], option: str) -> str | None:
    for position, argument in enumerate(arguments):
        if argument == option and position + 1 < len(arguments):
            return arguments[position + 1]
        if argument.startswith(f"{option}="):
            return argument.split("=", 1)[1]
    return None


def process_is_ours(pid: int, storage_root: Path) -> bool:
    """Whether a live process is this app's own, for this account.

    A pid alone cannot answer this, and a wrong answer is not cosmetic: it decides
    whether ``start`` starts anything and whether ``stop`` signals a process that
    belongs to somebody else. Two things have to hold. The process has to *be* this app
    rather than mention it, which is the program token rather than any later argument.
    And it has to be the app for *this* account, because a pid file can name a live app
    of another installation and that one is not this command's to signal.
    """

    if not process_exists(pid):
        return False
    arguments = process_arguments(pid)
    if arguments is None or _program_of(arguments) is None:
        return False
    try:
        environ = Path(f"/proc/{pid}/environ").read_bytes().decode("utf-8", "replace")
    except OSError:
        return False
    served = process_storage_root(arguments, environ)
    return served is not None and served == Path(storage_root).expanduser().resolve()


def arguments_are_ours(arguments: Sequence[str]) -> bool:
    """Whether a command line is this app's, from the arguments alone.

    The process has to *be* this app rather than mention it. One of the two shapes the
    product is started in qualifies: the executable itself as the first argument, or the
    module named by an interpreter's ``-m``. Anything else is refused, so an unrelated
    process whose arguments happen to contain this product's name — a shell in the
    repository, an editor with a path open, a test runner on a path under it — is left
    alone and read as not running.
    """

    return _program_of(arguments) is not None


def _is_entry_point(argument: str) -> bool:
    """Whether one argument names this app's executable or its module."""

    path = Path(argument)
    return any(name in (path.name, path.stem) for name in PROCESS_MARKERS)


def running_pid(storage_root: Path) -> int | None:
    """The pid the launcher recorded, while that process is still this app's.

    A pid file outlives its process, and the number it holds is reused, so the number
    alone is not a running app: the recorded process has to name itself as ours, for
    this account, before the record is believed.
    """

    try:
        pid = int(pid_file(storage_root).read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None
    return pid if process_is_ours(pid, storage_root) else None


def process_exists(pid: int) -> bool:
    """Whether a process still exists, without signalling it."""

    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def running_url(storage_root: Path) -> str | None:
    """The URL of a running app for this account, or None when there is not one.

    This is what a command checks before it decides to answer in process. A read of
    local state must not refuse itself because no app is up.
    """

    if running_pid(storage_root) is None:
        return None
    port = recorded_port(storage_root)
    return f"http://{UI_HOST}:{port}" if port is not None else None


def state(storage_root: Path) -> dict[str, Any]:
    """What this account's app is doing, for a status answer."""

    port = recorded_port(storage_root)
    pid = running_pid(storage_root)
    url = f"http://{UI_HOST}:{port}" if (pid is not None and port is not None) else None
    return {
        "running": pid is not None,
        "pid": pid,
        "port": port,
        "url": url,
        "log": str(log_path(storage_root)),
        "launcher": str(launcher_path(storage_root)),
    }


def start_app(
    storage_root: Path,
    *,
    port: int | None = None,
    open_browser: bool = False,
) -> dict[str, Any]:
    """The app up for this account, and what it did.

    An app already up is left alone: two apps over one account would each hold their
    own copy of every memory and neither would know about the other.
    """

    script = ensure_launcher(storage_root)
    existing = running_pid(storage_root)
    if existing is not None:
        current = state(storage_root)
        return {**current, "started": False, "note": "The app was already running."}
    # This script's own options come before the command it runs, because the command is
    # everything from the first non-option onward. The script appends the port it
    # actually claimed, so --port here names the port to ask for first rather than the
    # port the app will serve on.
    command = [str(script)]
    if port is not None:
        command.extend(["--port", str(port)])
    if open_browser:
        command.append("--open")
    command.extend([sys.executable, "-m", "memory_rag"])
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    return {
        **state(storage_root),
        "started": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
    }


def _may_be_signalled(pid: int) -> bool:
    """Whether a signal to this pid cannot reach this command or anything above it.

    A stale record that names the shell running `stop`, or one of its ancestors, would
    otherwise end the terminal the reader is holding. A group is never signalled for the
    same reason: one `-pid` would take a reader's shell with it, and pid 0 means the
    caller's whole process group while pid 1 is init, which is never this app.
    """

    if pid <= 1 or pid in {os.getpid(), os.getppid()}:
        return False
    return not _has_ancestor(pid)


def _has_ancestor(pid: int) -> bool:
    """Whether this process is somewhere above the one asking."""

    seen: set[int] = set()
    current = os.getpid()
    while current > 1 and current not in seen:
        seen.add(current)
        if current == pid:
            return True
        try:
            fields = (
                Path(f"/proc/{current}/stat")
                .read_text(encoding="utf-8")
                .rsplit(")", 1)[-1]
                .split()
            )
        except (OSError, IndexError):
            return False
        current = int(fields[1])
    return False


def _open_handle(pid: int) -> int | None:
    """Return a handle that keeps this exact process reachable, or None without one.

    A pidfd names the process rather than the number, so a number reused between the
    check and the signal is a different process and the signal cannot reach it. There is
    no fallback to the bare number: without a handle there is no proof left between the
    check and the signal, and a proof this command cannot make is a signal it does not
    send.
    """

    opener = getattr(os, "pidfd_open", None)
    if opener is None:  # pragma: no cover - Python without pidfd_open
        return None
    try:
        return int(opener(pid, 0))
    except OSError:
        return None


def _signal_handle(handle: int, number: int) -> bool:
    """Send one signal through a handle, and report whether it was sent."""

    sender = getattr(signal, "pidfd_send_signal", None)
    if sender is None:  # pragma: no cover - Python without pidfd_send_signal
        return False
    try:
        sender(handle, number)
    except OSError:
        return False
    return True


def stop_app(storage_root: Path) -> dict[str, Any]:
    """Stop this account's app, and report what answered.

    Nothing is signalled until the recorded pid has been proved to be this app's own
    process for this account, and the signal goes through a handle that names the
    process rather than the number. A record that fails either test is removed and
    reported instead, because a pid file that is stale is a fact about the file rather
    than a reason to signal whatever the machine runs under that number now.
    """

    if not launcher_path(storage_root).is_file() and not _record_exists(storage_root):
        return {
            "running": False,
            "stopped": False,
            "note": "There is no generated launcher, so no app was started from here.",
        }
    try:
        pid = int(pid_file(storage_root).read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        _clear_record(storage_root)
        return {
            **state(storage_root),
            "stopped": True,
            "note": "The pid record did not hold a number, so it was removed.",
        }

    if not process_is_ours(pid, storage_root):
        _clear_record(storage_root)
        return {
            **state(storage_root),
            "stopped": True,
            "note": (
                f"Pid {pid} is not this account's app, so it was left alone and its "
                "record was removed."
            ),
        }
    if not _may_be_signalled(pid):
        return {
            **state(storage_root),
            "stopped": False,
            "note": (
                f"Pid {pid} is this command or one of its ancestors, so it was not "
                "signalled."
            ),
        }

    handle = _open_handle(pid)
    if handle is None:
        return {
            **state(storage_root),
            "stopped": False,
            "note": (
                "This kernel or Python has no process handle (Linux 5.3 with Python "
                "3.9 or newer), so the app was left running rather than signalled by a "
                "number nothing proved."
            ),
        }
    try:
        # The handle pins the process, so this is a signal to the process that was
        # proved and not to a number that has since been handed to somebody else.
        sent = _signal_handle(handle, signal.SIGTERM)
        deadline = time.monotonic() + STOP_TIMEOUT_SECONDS
        while sent and process_exists(pid) and time.monotonic() < deadline:
            time.sleep(0.2)
        if sent and process_exists(pid):
            sent = _signal_handle(handle, signal.SIGKILL)
            waited = time.monotonic() + STOP_TIMEOUT_SECONDS
            while sent and process_exists(pid) and time.monotonic() < waited:
                time.sleep(0.2)
    finally:
        os.close(handle)

    stopped = sent and not process_exists(pid)
    if stopped:
        _clear_record(storage_root)
    return {
        **state(storage_root),
        "stopped": stopped,
        "note": (
            f"Stopped the app with pid {pid}."
            if stopped
            else f"Pid {pid} ignored SIGTERM and SIGKILL; remove it by hand."
        ),
    }


def _record_exists(storage_root: Path) -> bool:
    return pid_file(storage_root).is_file() or port_file(storage_root).is_file()


def _clear_record(storage_root: Path) -> None:
    """Forget a pid and a port, so nothing reads them as a running app."""

    pid_file(storage_root).unlink(missing_ok=True)
    port_file(storage_root).unlink(missing_ok=True)


__all__ = [
    "DEFAULT_UI_PORT",
    "LAUNCHER_MARKER",
    "LAUNCHER_NAME",
    "LINK_NAME",
    "LOG_NAME",
    "PROCESS_MARKERS",
    "STATE_DIRNAME",
    "STOP_TIMEOUT_SECONDS",
    "arguments_are_ours",
    "ensure_launcher",
    "ensure_link",
    "launcher_is_current",
    "launcher_path",
    "launcher_script",
    "link_path",
    "log_path",
    "pid_file",
    "port_file",
    "process_arguments",
    "process_exists",
    "process_is_ours",
    "process_storage_root",
    "recorded_port",
    "running_pid",
    "running_url",
    "start_app",
    "state",
    "state_root",
    "stop_app",
]
