"""Starting and stopping the app, and knowing whether it is up.

The launcher is a generated POSIX shell script rather than a call into this process,
for the same reason it is in the research app: choosing a free port and holding it
exclusively has to survive this process exiting, or two commands asked to start the app
at the same moment both decide the same port is free.

The state lives beside the account's global memory rather than inside a project,
because there is one app for the account and not one per project. A project's own
repository holds its local memory and nothing of the app's, which is what lets a
project be moved, copied, or shared without carrying a port number with it.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from .app import PID_FILE, PORT_FILE, UI_HOST

#: The directory under the storage root that holds the app's machine-local state.
STATE_DIRNAME = "app"
LAUNCHER_DIRECTORY = "bin"
LAUNCHER_NAME = "memory-rag-app.sh"
LOG_NAME = "memory-rag.log"
#: The port the app asks for first. A command that needs a fixed port says so, and the
#: script walks forward from here when this one is taken.
DEFAULT_UI_PORT = 5051
#: The project-root name a person double-clicks. It is a symlink, so it is a fact of
#: this machine rather than something a project carries between them.
LINK_NAME = "open-memory-rag-ui.sh"
#: The marker that says which build wrote the script. The version is part of it
#: because a template change within one product is exactly the case a bare product
#: name misses: the file would pass the check and run a command this build no longer
#: accepts, and the failure would appear only in a log nobody opens.
LAUNCHER_MARKER = "memory-rag-app"
#: How long `stop` waits after SIGTERM before it escalates.
STOP_TIMEOUT_SECONDS = 5.0


def state_root(storage_root: Path) -> Path:
    """Return the machine-local state directory for this account's app."""

    return storage_root / STATE_DIRNAME


def launcher_path(storage_root: Path) -> Path:
    """Return where the generated launcher lives."""

    return state_root(storage_root) / LAUNCHER_DIRECTORY / LAUNCHER_NAME


def log_path(storage_root: Path) -> Path:
    return state_root(storage_root) / LOG_NAME


def port_file(storage_root: Path) -> Path:
    return state_root(storage_root) / PORT_FILE


def pid_file(storage_root: Path) -> Path:
    return state_root(storage_root) / PID_FILE


_TEMPLATE = """#!/bin/sh
# {marker} {version}: generated by memory-rag. Machine-local, holds nothing of yours,
# safe to delete: the next `memory-rag start` writes a new one.
set -u

STATE="{state}"
# The storage root this launcher's own state lives under. It is handed to the app it
# starts, because a launcher that chose a port and wrote a pid file for one account
# while starting an app configured for another is two installations that agree about
# nothing, and the one that answers is whichever the environment happened to select.
STORAGE="{storage}"
PORT_FILE="$STATE/{port_file}"
PID_FILE="$STATE/{pid_file}"
LOG="$STATE/{log}"
LOCK="$STATE/start.lock"
DEFAULT_PORT={default_port}

mkdir -p "$STATE/logs" 2>/dev/null || true

free_port() {{
  # The first port at or above $1 with nothing listening on it, tried 200 times. A
  # port in TIME_WAIT after a stop is reusable, so this is a bind test rather than a
  # check of a file.
  candidate=$1
  tries=0
  while [ "$tries" -lt 200 ]; do
    if command -v python3 >/dev/null 2>&1; then
      if python3 -c "import socket,sys
s=socket.socket()
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
try:
    s.bind(('{host}', int(sys.argv[1])))
except OSError:
    sys.exit(1)
finally:
    s.close()" "$candidate" 2>/dev/null; then
        printf '%s' "$candidate"
        return 0
      fi
    fi
    candidate=$((candidate + 1))
    tries=$((tries + 1))
  done
  return 1
}}

stop_app() {{
  if [ ! -f "$PID_FILE" ]; then
    echo "memory-rag: no app is recorded as running."
    exit 0
  fi
  pid=$(cat "$PID_FILE" 2>/dev/null || true)
  case "$pid" in
    ''|*[!0-9]*)
      echo "memory-rag: the pid file does not hold a number; removing it."
      rm -f "$PID_FILE"
      exit 0
      ;;
  esac
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "memory-rag: no process is running with pid $pid; removing its record."
    rm -f "$PID_FILE" "$PORT_FILE"
    exit 0
  fi
  # The recorded pid has to still be this app's own process. A pid file outlives its
  # process and the number gets reused, so a stop that trusted the number alone would
  # signal whatever the machine happened to run next, which is a process this command
  # does not own and has no reason to touch.
  if [ -r "/proc/$pid/cmdline" ]; then
    if ! tr '\\0' '\\n' < "/proc/$pid/cmdline" 2>/dev/null | grep -qE '(^|/)(memory_rag|memory-rag)([.]py)?$'; then
      echo "memory-rag: pid $pid is not this app's process, so it was left alone;" \\
        "removing the record instead." >&2
      rm -f "$PID_FILE" "$PORT_FILE"
      exit 0
    fi
  fi
  kill -TERM "$pid" 2>/dev/null || true
  waited=0
  limit={stop_timeout}
  while [ "$waited" -lt "$limit" ]; do
    if ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$PID_FILE" "$PORT_FILE"
      echo "memory-rag: stopped the app with pid $pid."
      exit 0
    fi
    sleep 1
    waited=$((waited + 1))
  done
  kill -KILL "$pid" 2>/dev/null || true
  sleep 1
  if kill -0 "$pid" 2>/dev/null; then
    echo "memory-rag: pid $pid ignored SIGTERM and SIGKILL; remove it by hand." >&2
    exit 1
  fi
  rm -f "$PID_FILE" "$PORT_FILE"
  echo "memory-rag: stopped the app with pid $pid."
}}

case "${{1:-}}" in
  --stop)
    stop_app
    ;;
  --help|-h)
    echo "Generated by memory-rag. Takes --port N, --open, or --stop."
    ;;
esac

# One start at a time, or two commands pick the same port and one of them loses the
# claim after it has already written its pid file.
if ! mkdir "$LOCK" 2>/dev/null; then
  stale=$(cat "$LOCK/pid" 2>/dev/null || true)
  if [ -n "$stale" ] && ! kill -0 "$stale" 2>/dev/null; then
    rm -rf "$LOCK"
    mkdir "$LOCK" 2>/dev/null || exit 1
  else    echo "memory-rag: another start is already choosing a port; wait for it." >&2
    exit 1
  fi
fi
echo $$ > "$LOCK/pid"
trap 'rm -rf "$LOCK"' EXIT INT TERM

# The command to run is this script's arguments, so the options this script reads are
# taken off the front of them and the rest is left in place for the app. A loop that
# shifted every argument would consume the command too and run nothing at all.
requested=$DEFAULT_PORT
open_browser=no
command=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --port)
      shift
      requested=${{1:-$DEFAULT_PORT}}
      shift
      ;;
    --port=*)
      requested=${{1#--port=}}
      shift
      ;;
    --open|-o)
      open_browser=yes
      shift
      ;;
    --)
      shift
      command="$*"
      break
      ;;
    -*)
      echo "memory-rag: $1 is not an option this launcher takes." >&2
      exit 1
      ;;
    *)
      # The first argument that is not an option starts the command, and everything
      # from there on belongs to it.
      command="$*"
      break
      ;;
  esac
done

if [ -z "$command" ]; then
  echo "memory-rag: this launcher needs a command to run, e.g. the serve subcommand." >&2
  exit 1
fi

PORT=$(free_port "$requested")
if [ -z "$PORT" ]; then
  echo "memory-rag: no free port from $requested upward; pass --port to choose one." >&2
  exit 1
fi

# The command's own global option comes before the subcommand and the subcommand's own
# option after it, because that is the only order the parser accepts: a global option
# placed after `serve` is rejected outright, and an option the app owns placed before it
# is never read. Getting this order wrong fails into the log above and nowhere else, so
# the integration test runs this script as written rather than trusting it.
printf '%s' "$PORT" > "$PORT_FILE"

# The app is put in its own session when the system can do it, so that the shell that
# started it going away does not take it with it. A terminal that is closed, or a
# parent process group that is reaped, would otherwise end an app that was supposed to
# outlive the command. Without setsid the app still starts; it just lives as long as
# whatever started it, which is not what `memory-rag start` promises.
if command -v setsid >/dev/null 2>&1; then
  # shellcheck disable=SC2086
  setsid $command --storage-root "$STORAGE" serve --port "$PORT" >>"$LOG" 2>&1 &
else
  # shellcheck disable=SC2086
  $command --storage-root "$STORAGE" serve --port "$PORT" >>"$LOG" 2>&1 &
fi
app_pid=$!
printf '%s' "$app_pid" > "$PID_FILE"

# Wait for the port to answer rather than for the process to exist, because a process
# that has started and is still loading a model is not yet serving.
waited=0
while [ "$waited" -lt 120 ]; do
  if command -v python3 >/dev/null 2>&1; then
    if python3 -c "import socket,sys
s=socket.socket()
s.settimeout(1)
try:
    s.connect(('{host}', int(sys.argv[1])))
except OSError:
    sys.exit(1)
finally:
    s.close()" "$PORT" 2>/dev/null; then
      break
    fi
  fi
  if ! kill -0 "$app_pid" 2>/dev/null; then
    echo "memory-rag: the app exited before it served. Read $LOG" >&2
    rm -f "$PID_FILE" "$PORT_FILE"
    exit 1
  fi
  sleep 1
  waited=$((waited + 1))
done

case "$open_browser" in
  yes)
    command -v xdg-open >/dev/null 2>&1 && xdg-open "http://{host}:$PORT" >/dev/null 2>&1
    command -v open >/dev/null 2>&1 && open "http://{host}:$PORT" >/dev/null 2>&1
    ;;
esac

echo "memory-rag: the app is at http://{host}:$PORT"
echo "memory-rag: its log is $LOG"
exit 0
"""


def launcher_script(storage_root: Path) -> str:
    """Return the launcher this build would write."""

    from . import __version__

    return _TEMPLATE.format(
        marker=LAUNCHER_MARKER,
        version=__version__,
        state=state_root(storage_root),
        storage=storage_root,
        port_file=PORT_FILE,
        pid_file=PID_FILE,
        log=LOG_NAME,
        default_port=DEFAULT_UI_PORT,
        stop_timeout=int(STOP_TIMEOUT_SECONDS),
        host=UI_HOST,
    )


def ensure_launcher(storage_root: Path) -> Path:
    """Write the launcher if it is missing or was written by another build.

    The file is machine-local and holds nothing of the user's, so replacing it is safe.
    A file this build did not write may run a command this one no longer accepts, and
    running it would fail in a log nobody opens.
    """

    target = launcher_path(storage_root)
    if target.is_file() and launcher_is_current(target):
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(launcher_script(storage_root), encoding="utf-8")
    target.chmod(0o755)
    return target


def launcher_is_current(script: Path) -> bool:
    """Whether a launcher was written by this version of this build.

    The marker is a whole line rather than a substring, because a path or an argument
    may contain the same words and a substring match would read a stale file as
    current. The version is compared as well, so a template change rewrites the file
    rather than leaving an older command in place.
    """

    from . import __version__

    wanted = f"# {LAUNCHER_MARKER} {__version__}:"
    try:
        for line in script.read_text(encoding="utf-8").splitlines():
            if line.startswith(wanted):
                return True
    except OSError:
        return False
    return False


def link_path(project_root: Path) -> Path:
    """Return the double-clickable name inside a project."""

    return project_root / LINK_NAME


def ensure_link(project_root: Path, storage_root: Path) -> str:
    """Point a project's double-clickable name at the account's launcher.

    The link is machine-local and is never overwritten if it points somewhere else, so
    a project keeps whatever the user put there.
    """

    target = launcher_path(storage_root)
    link = link_path(project_root)
    if link.is_symlink():
        if os.readlink(link) == str(target):
            return "current"
        link.unlink()
    elif link.exists():
        return "left alone: a file of that name is already there"
    link.symlink_to(target)
    return "written"


def recorded_port(storage_root: Path) -> int | None:
    """The port the launcher recorded, or None when it recorded none."""

    try:
        return int(port_file(storage_root).read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None


#: The whole arguments a process of this app carries, as one word. A pid is only this
#: app's if its own argv says so, because a pid file outlives its process and the
#: number it holds is reused by whatever runs next: believing a stale record would make
#: a stopped app look running and a start refuse to start.
PROCESS_MARKERS = ("memory_rag", "memory-rag")


def process_is_ours(pid: int) -> bool:
    """Whether a live process is this app's own, by its arguments rather than by its
    number.

    A pid alone cannot answer this, and a wrong answer is not cosmetic: it decides
    whether ``start`` starts anything and whether ``stop`` signals a process that
    belongs to somebody else.
    """

    if not process_exists(pid):
        return False
    try:
        argv = Path(f"/proc/{pid}/cmdline").read_bytes().decode("utf-8", "replace")
    except OSError:
        # A process that ended between the check above and this read is not ours to
        # signal, and there is no portable way to ask on every system.
        return False
    arguments = [part for part in argv.split("\0") if part]
    return any(
        marker == Path(argument).stem or marker in Path(argument).name
        for argument in arguments
        for marker in PROCESS_MARKERS
    )


def running_pid(storage_root: Path) -> int | None:
    """The pid the launcher recorded, while that process is still this app's.

    A pid file outlives its process, and the number it holds is reused, so the number
    alone is not a running app: the recorded process has to name itself as ours before
    the record is believed.
    """

    try:
        pid = int(pid_file(storage_root).read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None
    return pid if process_is_ours(pid) else None


def process_exists(pid: int) -> bool:
    """Whether a process still exists, without signalling it."""

    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def running_url(storage_root: Path) -> str | None:
    """The URL of a running app for this account, or None when there is not one.

    This is what a command checks before it decides to answer in process. A read of
    local state must not refuse itself because no app is up.
    """

    if running_pid(storage_root) is None:
        return None
    port = recorded_port(storage_root)
    return f"http://{UI_HOST}:{port}" if port is not None else None


def state(storage_root: Path) -> dict[str, Any]:
    """What this account's app is doing, for a status answer."""

    port = recorded_port(storage_root)
    pid = running_pid(storage_root)
    url = f"http://{UI_HOST}:{port}" if (pid is not None and port is not None) else None
    return {
        "running": pid is not None,
        "pid": pid,
        "port": port,
        "url": url,
        "log": str(log_path(storage_root)),
        "launcher": str(launcher_path(storage_root)),
    }


def start_app(
    storage_root: Path,
    *,
    port: int | None = None,
    open_browser: bool = False,
) -> dict[str, Any]:
    """The app up for this account, and what it did.

    An app already up is left alone: two apps over one account would each hold their
    own copy of every memory and neither would know about the other.
    """

    script = ensure_launcher(storage_root)
    existing = running_pid(storage_root)
    if existing is not None:
        current = state(storage_root)
        return {**current, "started": False, "note": "The app was already running."}
    # This script's own options come before the command it runs, because the command is
    # everything from the first non-option onward. The script appends the port it
    # actually claimed, so --port here names the port to ask for first rather than the
    # port the app will serve on.
    command = [str(script)]
    if port is not None:
        command.extend(["--port", str(port)])
    if open_browser:
        command.append("--open")
    command.extend([sys.executable, "-m", "memory_rag"])
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    return {
        **state(storage_root),
        "started": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
    }


def stop_app(storage_root: Path) -> dict[str, Any]:
    """Stop the app and everything it started, and report what answered."""

    script = launcher_path(storage_root)
    if not script.is_file():
        return {
            "running": False,
            "stopped": False,
            "note": "There is no generated launcher, so no app was started from here.",
        }
    completed = subprocess.run(
        [str(script), "--stop"], capture_output=True, text=True, check=False
    )
    return {
        **state(storage_root),
        "stopped": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
    }


__all__ = [
    "DEFAULT_UI_PORT",
    "LAUNCHER_MARKER",
    "LAUNCHER_NAME",
    "LINK_NAME",
    "LOG_NAME",
    "STATE_DIRNAME",
    "STOP_TIMEOUT_SECONDS",
    "ensure_launcher",
    "ensure_link",
    "launcher_is_current",
    "launcher_path",
    "launcher_script",
    "link_path",
    "log_path",
    "pid_file",
    "port_file",
    "process_exists",
    "recorded_port",
    "running_pid",
    "running_url",
    "start_app",
    "state",
    "state_root",
    "stop_app",
]
